name: com.example.flutter_cubit_app
description: A simple Flutter application using the Cubit pattern for state management. The app has a login screen with email and password fields, and a home screen with a logout button.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true